"""Slack notifier — posts Block Kit investigation reports to a webhook URL.

Secrets are fetched from AWS SSM via :func:`common.secrets.get_slack_webhook_url`.
HTTP delivery uses only the stdlib ``urllib.request`` module so no extra
dependency is required.
"""

from __future__ import annotations

import json
import urllib.request
from datetime import UTC, datetime
from typing import Any

from agent.models.finding import Finding, Recommendation, Severity
from common.config import AgentConfig
from common.logger import get_logger
from common.secrets import get_slack_webhook_url

__all__ = ["SlackNotifier"]

_SEVERITY_EMOJI: dict[Severity, str] = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🟢",
}

_MAX_FINDINGS = 10
_DESCRIPTION_MAX_LEN = 150


def _truncate(text: str, max_len: int) -> str:
    """Truncate *text* to *max_len* chars, appending '…' if shortened.

    Args:
        text: Input string.
        max_len: Maximum allowed character length.

    Returns:
        Original string or a truncated version ending with the ellipsis char.
    """
    if len(text) <= max_len:
        return text
    return text[: max_len - 1] + "…"


def _finding_blocks(finding: Finding) -> list[dict[str, Any]]:
    """Build the Block Kit blocks for a single Finding.

    Args:
        finding: Validated Finding instance.

    Returns:
        List of Slack Block Kit block dicts for this finding.
    """
    emoji = _SEVERITY_EMOJI.get(finding.severity, "⚪")
    usd = finding.estimated_monthly_usd
    confidence_pct = int(finding.confidence * 100)

    blocks: list[dict[str, Any]] = [
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"{emoji} *{finding.title}*  ~${usd:.2f}/mo",
            },
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": (
                        f"{_truncate(finding.description, _DESCRIPTION_MAX_LEN)}"
                        f"  |  confidence: {confidence_pct}%"
                    ),
                }
            ],
        },
    ]

    if finding.remediation_command:
        blocks.append(
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": f"```{finding.remediation_command}```",
                    }
                ],
            }
        )

    return blocks


def _build_payload(
    recommendation: Recommendation,
    investigation_id: str,
) -> dict[str, Any]:
    """Construct the full Slack Block Kit message payload.

    Args:
        recommendation: Completed Recommendation object.
        investigation_id: UUID string for this investigation run.

    Returns:
        Dict ready to be serialised as the POST body to the webhook.
    """
    today = datetime.now(UTC).strftime("%Y-%m-%d")
    timestamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    total = recommendation.total_estimated_monthly_usd

    blocks: list[dict[str, Any]] = [
        # Header
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"🔍 FinOps Weekly Report — {today}",
                "emoji": True,
            },
        },
        # Investigation ID context
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"Investigation ID: `{investigation_id}`",
                }
            ],
        },
        # Executive summary section
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": (
                    f"*💰 Total potential savings: ${total:.2f}/month*\n{recommendation.summary}"
                ),
            },
        },
        {"type": "divider"},
    ]

    # Per-finding blocks (sorted desc by estimated_monthly_usd, max 10)
    sorted_findings = sorted(
        recommendation.findings,
        key=lambda f: f.estimated_monthly_usd,
        reverse=True,
    )[:_MAX_FINDINGS]

    for finding in sorted_findings:
        blocks.extend(_finding_blocks(finding))

    blocks.append({"type": "divider"})

    # Footer
    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"Generated by FinOps Agent • {timestamp}",
                }
            ],
        }
    )

    return {"blocks": blocks}


class SlackNotifier:
    """Posts FinOps investigation reports to Slack via an incoming webhook.

    The webhook URL is fetched from AWS SSM Parameter Store at notification
    time so the secret is never stored in memory longer than necessary.

    Attributes:
        _config: AgentConfig providing the AWS region for SSM lookup.
        _log: Bound structlog logger.
    """

    def __init__(self, config: AgentConfig | None = None) -> None:
        """Initialise the notifier from agent configuration.

        Args:
            config: Optional AgentConfig instance.  A default instance is
                created from environment variables when not supplied.
        """
        self._config: AgentConfig = config or AgentConfig()
        self._log = get_logger(__name__)

    def notify(self, recommendation: Recommendation, investigation_id: str) -> None:
        """Post a Block Kit investigation report to Slack.

        Silently skips if ``recommendation.findings`` is empty to avoid
        spam on clean runs.  All HTTP/SSM errors are caught, logged with
        the event key ``slack_notification_failed``, and suppressed so
        that a notification failure never blocks the investigation result.

        Args:
            recommendation: Completed Recommendation object to report on.
            investigation_id: UUID string identifying this investigation run.
        """
        if not recommendation.findings:
            self._log.info(
                "slack_notifier_skipped_empty_findings",
                investigation_id=investigation_id,
            )
            return

        try:
            webhook_url = get_slack_webhook_url(region=self._config.aws_region)
            payload = _build_payload(recommendation, investigation_id)
            body = json.dumps(payload).encode("utf-8")

            req = urllib.request.Request(
                url=webhook_url,
                data=body,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=10) as response:  # noqa: S310
                status = response.status

            self._log.info(
                "slack_notification_sent",
                investigation_id=investigation_id,
                findings_count=len(recommendation.findings),
                http_status=status,
            )

        except Exception as exc:  # noqa: BLE001
            self._log.error(
                "slack_notification_failed",
                investigation_id=investigation_id,
                error=str(exc),
            )
